import { IHotel, IHotelBooking } from "./model/Hotel";
import { IUser } from "./model/user";
import { ERoomType, EUserRoles } from "./types/enum";

export const Duser : IUser = {
  id: 1,
  avt: "https://i.pinimg.com/736x/64/f7/8d/64f78daedff642c605dc3bab2604e832.jpg",
  name: "Lâm Hà",
  username: "john_doe",
  email: "john.doe@example.com",
  password: "hashed_password_123",
  gender: true, 
  phoneNumber: "0903536212",
  birthday: new Date("1991-03-25"),
  address: "123 Main St, City, Country",
  NIDNumber: "123456789",
  idToken: "token_12345",
  cartId: [101],
  ratings: [
    { hotelId: 1, rating: 5, comment: "Excellent stay!" },
    { hotelId: 2, rating: 4, comment: "Good experience" },
  ],
  chatFromUser: [1, 2, 3], 
  chatToUser: [2, 3, 4],
  hotels: [1, 2], 
  roles: EUserRoles.ADMIN, 
  status: true, 
};

export const DCart = [
  {
    id: 101,
    userId : 1,
    hotelBooking: 1,
    quantity: 1,
    price: 100,
    amount: 100,
    paymentMethod: "CASH",
    paymentDate: new Date("2023-12-01"),
    createdAt: new Date("2023-12-01"),
    paymentStatus: false,
  },
  {
    id: 102,
    userId : 1,
    hotelBooking: 2,
    quantity: 2,
    price: 200,
    amount: 400,
    paymentMethod: "CASH",
    paymentDate: new Date("2023-12-02"),
    createdAt: new Date("2023-12-02"),
    paymentStatus: false,
  },
];


export const DreviewItems = [
  {
    id: 1,
    hotelName: "Hotel Paradise",
    review: "Amazing experience, great service!",
    date: "2023-12-01",
    rating: 5,
  },
  {
    id: 2,
    hotelName: "Sunset Inn",
    review: "Beautiful views and comfortable rooms.",
    date: "2023-11-15",
    rating: 4,
  },
  {
    id: 3,
    hotelName: "Mountain Retreat",
    review: "Peaceful location with excellent amenities.",
    date: "2023-10-20",
    rating: 5,
  },
  {
    id: 4,
    hotelName: "City Lights Hotel",
    review: "Convenient location but rooms were a bit small.",
    date: "2023-09-05",
    rating: 3,
  },
  {
    id: 5,
    hotelName: "Oceanview Resort",
    review: "Stunning ocean views and friendly staff.",
    date: "2023-08-12",
    rating: 5,
  },
  {
    id: 6,
    hotelName: "Grand Plaza",
    review: "Luxurious rooms with top-notch facilities.",
    date: "2023-07-22",
    rating: 4,
  },
  {
    id: 7,
    hotelName: "Budget Stay",
    review: "Affordable prices but limited services.",
    date: "2023-06-30",
    rating: 2,
  },
  {
    id: 8,
    hotelName: "Lakeside Lodge",
    review: "Charming place with beautiful lake views.",
    date: "2023-05-18",
    rating: 4,
  },
  {
    id: 9,
    hotelName: "Urban Comfort",
    review: "Modern design and very clean rooms.",
    date: "2023-04-25",
    rating: 5,
  },
  {
    id: 10,
    hotelName: "Historic Inn",
    review: "Rich history and unique architecture.",
    date: "2023-03-14",
    rating: 4,
  },
  {
    id: 11,
    hotelName: "EcoStay Hotel",
    review: "Great eco-friendly practices and comfortable beds.",
    date: "2023-02-10",
    rating: 5,
  },
  {
    id: 12,
    hotelName: "Traveler's Haven",
    review: "Perfect location for exploring the city.",
    date: "2023-01-05",
    rating: 4,
  },
];


export const DLocation = [
  {
    name: "Hội An",
    address: "Quảng Nam, Việt Nam",
  },
  {
    name: "Đà Nẵng",
    address: "Việt Nam",
  },
  {
    name: "Huế",
    address: "Thừa Thiên Huế, Việt Nam",
  },
  {
    name: "Nha Trang",
    address: "Khánh Hòa, Việt Nam",
  },
  {
    name: "Đà Lạt",
    address: "Lâm Đồng, Việt Nam",
  },
  {
    name: "TP. Hồ Chí Minh",
    address: "Việt Nam",
  },
  {
    name: "Hà Nội",
    address: "Việt Nam",
  },
];

export const hotelBookings: IHotelBooking[] = [
  {
    id: 1,
    user: { id: 101, name: "Nguyễn Văn A" },
    hotel: { id: 11, name: "Khách sạn Hội An Boutique" },
    checkInDate: new Date("2025-02-01"),
    checkOutDate: new Date("2025-02-05"),
    status: true,
    hotelBookingRooms: [{ id: 1 }],
  },
  {
    id: 2,
    user: { id: 102, name: "Trần Thị B" },
    hotel: { id: 12, name: "Khách sạn Minh Quang" },
    checkInDate: new Date("2025-02-10"),
    checkOutDate: new Date("2025-02-12"),
    status: true,
    hotelBookingRooms: [{ id: 2 }],
  },
];

export const DHotel: IHotel[] = [
  {
    id: 11,
    name: "Khách sạn Hội An Boutique",
    description: "Khách sạn boutique sang trọng với kiến trúc truyền thống và dịch vụ cao cấp.",
    price: 200.0,
    imageUrl: "https://i.pinimg.com/236x/57/89/44/578944fec96bc11d738bb187b74fb8c3.jpg",
    location: "Hội An",
    address: "Số 10 Trần Phú, Phường Minh An, Hội An",
    rating: 3.7,
    roomList: [
      {
        id: 1,
        numberRoom: 101,
        roomType: ERoomType.STANDARD,
        price: 100,
        maxOccupancy: 2,
        quantityRoom: 5,
        status: true,
        singleBed: 1,
        doubleBed: 1,
        hotelBookingRooms: [
          {
            id: 1,
            numRoom: 1,
            pricePerRoom: 100,
            hotelBooking: {
              id: 101,
              checkInDate: new Date("2025-02-01"),
              checkOutDate: new Date("2025-02-05"),
              customerName: "Nguyễn Văn A",
              customerEmail: "nguyenvana@example.com",
            },
          },
        ],
      },
      {
        id: 2,
        numberRoom: 102,
        roomType: ERoomType.STANDARD,
        price: 120,
        maxOccupancy: 3,
        quantityRoom: 2,
        status: true,
        singleBed: 1,
        doubleBed: 2,
        hotelBookingRooms: [
          {
            id: 2,
            numRoom: 1,
            pricePerRoom: 120,
            hotelBooking: {
              id: 102,
              checkInDate: new Date("2025-02-10"),
              checkOutDate: new Date("2025-02-12"),
              customerName: "Trần Thị B",
              customerEmail: "tranthib@example.com",
            },
          },
        ],
      },
      {
        id: 3,
        numberRoom: 103,
        roomType: ERoomType.DELUXE,
        price: 150,
        maxOccupancy: 2,
        quantityRoom: 4,
        status: true,
        singleBed: 2,
        doubleBed: 0,
        hotelBookingRooms: [
          {
            id: 3,
            numRoom: 1,
            pricePerRoom: 150,
            hotelBooking: {
              id: 103,
              checkInDate: new Date("2025-02-15"),
              checkOutDate: new Date("2025-02-20"),
              customerName: "Nguyễn Thị C",
              customerEmail: "nguyenthic@example.com",
            },
          },
        ],
      },
      {
        id: 4,
        numberRoom: 104,
        roomType: ERoomType.DELUXE,
        price: 180,
        maxOccupancy: 4,
        quantityRoom: 3,
        status: true,
        singleBed: 2,
        doubleBed: 1,
        hotelBookingRooms: [
          {
            id: 4,
            numRoom: 1,
            pricePerRoom: 180,
            hotelBooking: {
              id: 104,
              checkInDate: new Date("2025-02-20"),
              checkOutDate: new Date("2025-02-25"),
              customerName: "Lê Minh D",
              customerEmail: "leminhd@example.com",
            },
          },
        ],
      },
    ],
  },
  {
    id: 12,
    name: "Khách sạn Minh Quang",
    description: "Nằm gần phố cổ, cung cấp phòng nghỉ tiện nghi và view sông Hoài tuyệt đẹp.",
    price: 150.0,
    imageUrl: "https://example.com/images/minhquang.jpg",
    location: "Hội An",
    address: "Số 25 Nguyễn Thái Học, Phường Minh An, Hội An",
    rating: 2.8,
    roomList: [
      {
        id: 5,
        numberRoom: 105,
        roomType: ERoomType.STANDARD,
        price: 110,
        maxOccupancy: 2,
        quantityRoom: 4,
        status: true,
        singleBed: 1,
        doubleBed: 1,
        hotelBookingRooms: [
          {
            id: 5,
            numRoom: 1,
            pricePerRoom: 110,
            hotelBooking: {
              id: 105,
              checkInDate: new Date("2025-02-10"),
              checkOutDate: new Date("2025-02-12"),
              customerName: "Vũ Minh E",
              customerEmail: "vuminhe@example.com",
            },
          },
        ],
      },
      {
        id: 6,
        numberRoom: 106,
        roomType: ERoomType.DELUXE,
        price: 140,
        maxOccupancy: 3,
        quantityRoom: 3,
        status: true,
        singleBed: 1,
        doubleBed: 2,
        hotelBookingRooms: [
          {
            id: 6,
            numRoom: 1,
            pricePerRoom: 140,
            hotelBooking: {
              id: 106,
              checkInDate: new Date("2025-02-15"),
              checkOutDate: new Date("2025-02-17"),
              customerName: "Đỗ Thị F",
              customerEmail: "dothif@example.com",
            },
          },
        ],
      },
    ],
  },
  // Thêm nhiều khách sạn và phòng khác nếu cần
];


export const DRoom = [
  {
    id: 1,
    numberRoom: 101,
    roomType: ERoomType.STANDARD,
    price: 100,
    maxOccupancy: 2,
    quantityRoom: 5,
    status: true,
    singleBed: 1,
    doubleBed: 1,
    hotel: "hotel_1",
    image: "room_101.jpg",
    rating: 4.5,
  },
  {
    id: 2,
    numberRoom: 102,
    roomType: ERoomType.STANDARD,
    price: 120,
    maxOccupancy: 3,
    quantityRoom: 2,
    status: true,
    singleBed: 1,
    doubleBed: 2,
    hotel: "hotel_1",
    image: "room_102.jpg",
    rating: 4.2,
  },
  {
    id: 3,
    numberRoom: 103,
    roomType: ERoomType.STANDARD,
    price: 150,
    maxOccupancy: 4,
    quantityRoom: 3,
    status: true,
    singleBed: 2,
    doubleBed: 1,
    hotel: "hotel_1",
    image: "room_103.jpg",
    rating: 4.7,
  },
  {
    id: 4,
    numberRoom: 104,
    roomType: ERoomType.DELUXE,
    price: 80,
    maxOccupancy: 2,
    quantityRoom: 4,
    status: false,
    singleBed: 1,
    doubleBed: 4,
    hotel: "hotel_2",
    image: "room_104.jpg",
    rating: 3.8,
  },
  {
    id: 5,
    numberRoom: 105,
    roomType: ERoomType.DELUXE,
    price: 200,
    maxOccupancy: 5,
    quantityRoom: 2,
    status: true,
    singleBed: 2,
    doubleBed: 3,
    hotel: "hotel_2",
    image: "room_105.jpg",
    rating: 4.9,
  },
];

export const DHotelBooking = [
  {
    id: 1,
    user: { id: 101, name: "Nguyễn Văn A" },
    hotel: { id: "hotel_1", name: "Khách sạn ABC" },
    checkInDate: "2025-02-01",
    checkOutDate: "2025-02-05",
    bookingDate: "2025-01-15",
    status: true,
    hotelBookingRooms: [1],
    ratings: [{ id: 1, roomId: 1, rating: 5 }],
  },
  {
    id: 2,
    user: { id: 102, name: "Trần Thị B" },
    hotel: { id: 11, name: "Khách sạn Hội An Boutique" },
    checkInDate: "2025-02-10",
    checkOutDate: "2025-02-12",
    bookingDate: "2025-01-18",
    status: true,
    hotelBookingRooms: [2],
    ratings: [{ id: 2, roomId: 5, rating: 4 }],
  },
];

export const DHotelBookingRoom = [
  {
    id: 1,
    room: {
      id: 1,
      numberRoom: 101,
      roomType: "STANDARD",
      price: 100,
      maxOccupancy: 2,
      quantityRoom: 5,
      status: true,
    },
    hotelBooking: {
      id: 1,
      user: { id: 101, name: "Nguyễn Văn A" },
      hotel: { id: 11, name: "Khách sạn Hội An Boutique" },
    },
    numRoom: 2,
    pricePerRoom: 100,
  },
  {
    id: 2,
    room: {
      id: 5,
      numberRoom: 105,
      roomType: "DELUXE",
      price: 200,
      maxOccupancy: 5,
      quantityRoom: 2,
      status: true,
    },
    hotelBooking: {
      id: 2,
      user: { id: 102, name: "Trần Thị B" },
      hotel: { id: 11, name: "Khách sạn Hội An Boutique" },
    },
    numRoom: 1,
    pricePerRoom: 200,
  },
];
