import { IHotel } from "./types";
import { ERoomType } from "./types/enum";

export const Duser = {
  avar: "https://i.pinimg.com/736x/64/f7/8d/64f78daedff642c605dc3bab2604e832.jpg",
  name: "Nguyễn Hà",
};

export const DreviewItems = [
  {
    id: 1,
    hotelName: "Hotel Paradise",
    review: "Amazing experience, great service!",
    date: "2023-12-01",
    rating: 5,
  },
  {
    id: 2,
    hotelName: "Sunset Inn",
    review: "Beautiful views and comfortable rooms.",
    date: "2023-11-15",
    rating: 4,
  },
  {
    id: 3,
    hotelName: "Mountain Retreat",
    review: "Peaceful location with excellent amenities.",
    date: "2023-10-20",
    rating: 5,
  },
  {
    id: 4,
    hotelName: "City Lights Hotel",
    review: "Convenient location but rooms were a bit small.",
    date: "2023-09-05",
    rating: 3,
  },
  {
    id: 5,
    hotelName: "Oceanview Resort",
    review: "Stunning ocean views and friendly staff.",
    date: "2023-08-12",
    rating: 5,
  },
  {
    id: 6,
    hotelName: "Grand Plaza",
    review: "Luxurious rooms with top-notch facilities.",
    date: "2023-07-22",
    rating: 4,
  },
  {
    id: 7,
    hotelName: "Budget Stay",
    review: "Affordable prices but limited services.",
    date: "2023-06-30",
    rating: 2,
  },
  {
    id: 8,
    hotelName: "Lakeside Lodge",
    review: "Charming place with beautiful lake views.",
    date: "2023-05-18",
    rating: 4,
  },
  {
    id: 9,
    hotelName: "Urban Comfort",
    review: "Modern design and very clean rooms.",
    date: "2023-04-25",
    rating: 5,
  },
  {
    id: 10,
    hotelName: "Historic Inn",
    review: "Rich history and unique architecture.",
    date: "2023-03-14",
    rating: 4,
  },
  {
    id: 11,
    hotelName: "EcoStay Hotel",
    review: "Great eco-friendly practices and comfortable beds.",
    date: "2023-02-10",
    rating: 5,
  },
  {
    id: 12,
    hotelName: "Traveler's Haven",
    review: "Perfect location for exploring the city.",
    date: "2023-01-05",
    rating: 4,
  },
];

const FeaturedHotels = [
  {
    id: 1,
    name: "Hotel Sunshine",
    description: "Enjoy a sunny stay with excellent amenities.",
    price: "$120/night",
    imageUrl:
      "https://i.pinimg.com/736x/70/9a/a6/709aa615268c9ebd7940c9a14e2c1e47.jpg",
    location: "Đà Nẵng, Việt Nam",
  },
  {
    id: 2,
    name: "Mountain View Resort",
    description: "Experience serene mountain views and fresh air.",
    price: "$150/night",
    imageUrl:
      "https://i.pinimg.com/736x/70/9a/a6/709aa615268c9ebd7940c9a14e2c1e47.jpg",
    location: "Đà Lạt, Việt Nam",
  },
  {
    id: 3,
    name: "Sea Breeze Hotel",
    description: "Relax by the sea with our top-notch services.",
    price: "$180/night",
    imageUrl:
      "https://i.pinimg.com/736x/70/9a/a6/709aa615268c9ebd7940c9a14e2c1e47.jpg",
    location: "Nha Trang, Việt Nam",
  },
];

export const DLocation = [
  {
    locationName: "Hội An",
    locationAddress: "Quảng Nam, Việt Nam",
    img: "https://i.pinimg.com/474x/93/f5/79/93f579a38abdce145585ce5aef0160fd.jpg",
  },
  {
    locationName: "Đà Nẵng",
    locationAddress: "Việt Nam",
    img: "https://i.pinimg.com/236x/69/ed/1a/69ed1ab7eea1b75a04105f4de8a145e9.jpg",
  },
  {
    locationName: "Huế",
    locationAddress: "Thừa Thiên Huế, Việt Nam",
    img: "https://i.pinimg.com/236x/45/03/2e/45032e4dede478dd302753bf1f305638.jpg",
  },
  {
    locationName: "Nha Trang",
    locationAddress: "Khánh Hòa, Việt Nam",
    img: "https://i.pinimg.com/236x/60/d0/f3/60d0f31bd03546c7cf54075eb7be646b.jpg",
  },
  {
    locationName: "Đà Lạt",
    locationAddress: "Lâm Đồng, Việt Nam",
    img: "https://i.pinimg.com/236x/78/29/a8/7829a8d8967bf8408875f3d40e4aa5ee.jpg",
  },
  {
    locationName: "TP. Hồ Chí Minh",
    locationAddress: "Việt Nam",
    img: "https://i.pinimg.com/236x/47/ab/81/47ab8134011b1ce2bc3727aa07671bc6.jpg",
  },
  {
    locationName: "Hà Nội",
    locationAddress: "Việt Nam",
    img: "https://i.pinimg.com/236x/87/9a/a0/879aa0d98eab8913cdab628e0ba35be7.jpg",
  },
];

export const DHotel: IHotel[] = [
  {
    id: 11,
    name: "Khách sạn Hội An Boutique",
    description:
      "Khách sạn boutique sang trọng với kiến trúc truyền thống và dịch vụ cao cấp.",
    price: 200.0,
    imageUrl:
      "https://i.pinimg.com/236x/57/89/44/578944fec96bc11d738bb187b74fb8c3.jpg",
    location: "Hội An",
    address: "Số 10 Trần Phú, Phường Minh An, Hội An",
    rating: 3.7,
    roomList: [
      {
        id: 1,
        numberRoom: 101,
        roomType: ERoomType.STANDARD,
        price: 100,
        maxOccupancy: 2,
        quantityRoom: 5,
        status: true,
        singleBed: 1,
        doubleBed: 1,
      },
      {
        id: 2,
        numberRoom: 102,
        roomType: ERoomType.STANDARD,
        price: 120,
        maxOccupancy: 3,
        quantityRoom: 2,
        status: true,
        singleBed: 1,
        doubleBed: 2,
      },
      {
        id: 3,
        numberRoom: 103,
        roomType: ERoomType.STANDARD,
        price: 150,
        maxOccupancy: 4,
        quantityRoom: 3,
        status: true,
        singleBed: 2,
        doubleBed: 1,
      },
      {
        id: 4,
        numberRoom: 104,
        roomType: ERoomType.DELUXE,
        price: 80,
        maxOccupancy: 2,
        quantityRoom: 4,
        status: false,
        singleBed: 1,
        doubleBed: 4,
      },
      {
        id: 5,
        numberRoom: 105,
        roomType: ERoomType.DELUXE,
        price: 200,
        maxOccupancy: 5,
        quantityRoom: 2,
        status: true,
        singleBed: 2,
        doubleBed: 3,
      },
    ],
  },
  {
    id: 12,
    name: "Khách sạn Minh Quang",
    description:
      "Nằm gần phố cổ, cung cấp phòng nghỉ tiện nghi và view sông Hoài tuyệt đẹp.",
    price: 150.0,
    imageUrl: "https://example.com/images/minhquang.jpg",
    location: "Hội An",
    address: "Số 25 Nguyễn Thái Học, Phường Minh An, Hội An",
    rating: 2.8,
  },
  {
    id: 13,
    name: "Resort Đại Lộc",
    description:
      "Resort nghỉ dưỡng với bể bơi ngoài trời và khu vườn xanh mát.",
    price: 180.0,
    imageUrl: "https://example.com/images/dailoc_resort.jpg",
    location: "Hội An",
    address: "Khu Hà My, Phường Điện Dương, Hội An",
    rating: 4.5,
  },
  {
    id: 14,
    name: "Khách sạn An Bình",
    description:
      "Không gian yên tĩnh, thích hợp cho gia đình và du khách tìm kiếm sự thư giãn.",
    price: 170.0,
    imageUrl: "https://example.com/images/anbinh.jpg",
    location: "Hội An",
    address: "Số 36 Trần Cao Vân, Phường Cẩm Phô, Hội An",
    rating: 2.0,
  },
  {
    id: 15,
    name: "Khách sạn Lãng Yên",
    description:
      "Thiết kế hiện đại kết hợp nét truyền thống, cung cấp nhiều tiện ích cho khách hàng.",
    price: 220.0,
    imageUrl: "https://example.com/images/langyen.jpg",
    location: "Hội An",
    address: "Số 58 Lý Thường Kiệt, Phường Sơn Phong, Hội An",
    rating: 3.2,
  },
  {
    id: 16,
    name: "Khách sạn Thủy Vân",
    description:
      "View biển tuyệt đẹp, dịch vụ chuyên nghiệp và phòng nghỉ tiện nghi.",
    price: 250.0,
    imageUrl: "https://example.com/images/thuyvan.jpg",
    location: "Hội An",
    address: "Biển Cửa Đại, Phường Cẩm An, Hội An",
    rating: 4.9,
  },
  {
    id: 17,
    name: "Khách sạn Hoa Hồng",
    description:
      "Không gian lãng mạn, phù hợp cho các cặp đôi và kỳ nghỉ cuối tuần.",
    price: 190.0,
    imageUrl: "https://example.com/images/hoahong.jpg",
    location: "Hội An",
    address: "Số 22 Hoàng Diệu, Phường Sơn Phong, Hội An",
    rating: 3.0,
  },
  {
    id: 18,
    name: "Khách sạn Bình Minh",
    description:
      "Khách sạn hiện đại với nhiều tiện ích như gym, spa và nhà hàng.",
    price: 210.0,
    imageUrl: "https://example.com/images/binhminh.jpg",
    location: "Hội An",
    address: "Số 77 Phan Chu Trinh, Phường Minh An, Hội An",
    rating: 1.8,
  },
  {
    id: 19,
    name: "Khách sạn Phương Đông",
    description: "Kết hợp giữa phong cách phương Đông và tiện nghi hiện đại.",
    price: 230.0,
    imageUrl: "https://example.com/images/phuongdong.jpg",
    location: "Hội An",
    address: "Số 6 Bà Triệu, Phường Cẩm Phô, Hội An",
    rating: 4.1,
  },
  {
    id: 20,
    name: "Khách sạn Thiên Nhiên",
    description:
      "Nằm giữa thiên nhiên, cung cấp các hoạt động ngoài trời và nghỉ dưỡng.",
    price: 240.0,
    imageUrl: "https://example.com/images/thiennhien.jpg",
    location: "Hội An",
    address: "Số 50 Nguyễn Duy Hiệu, Phường Cẩm Châu, Hội An",
    rating: 2.9,
  },
];

export const DRoom = [
  {
    id: 1,
    numberRoom: 101,
    roomType: "STANDARD",
    price: 100,
    maxOccupancy: 2,
    quantityRoom: 5,
    status: true,
    singleBed: 1,
    doubleBed: 1,
    hotel: "hotel_1",
    image: "room_101.jpg",
    rating: 4.5,
  },
  {
    id: 2,
    numberRoom: 102,
    roomType: "STANDARD",
    price: 120,
    maxOccupancy: 3,
    quantityRoom: 2,
    status: true,
    singleBed: 1,
    doubleBed: 2,
    hotel: "hotel_1",
    image: "room_102.jpg",
    rating: 4.2,
  },
  {
    id: 3,
    numberRoom: 103,
    roomType: "STANDARD",
    price: 150,
    maxOccupancy: 4,
    quantityRoom: 3,
    status: true,
    singleBed: 2,
    doubleBed: 1,
    hotel: "hotel_1",
    image: "room_103.jpg",
    rating: 4.7,
  },
  {
    id: 4,
    numberRoom: 104,
    roomType: "DELUXE",
    price: 80,
    maxOccupancy: 2,
    quantityRoom: 4,
    status: false,
    singleBed: 1,
    doubleBed: 4,
    hotel: "hotel_2",
    image: "room_104.jpg",
    rating: 3.8,
  },
  {
    id: 5,
    numberRoom: 105,
    roomType: "DELUXE",
    price: 200,
    maxOccupancy: 5,
    quantityRoom: 2,
    status: true,
    singleBed: 2,
    doubleBed: 3,
    hotel: "hotel_2",
    image: "room_105.jpg",
    rating: 4.9,
  },
];

export const DHotelBooking = [
  {
    id: 1,
    user: { id: 101, name: "Nguyễn Văn A" },
    hotel: { id: "hotel_1", name: "Khách sạn ABC" },
    checkInDate: "2025-02-01",
    checkOutDate: "2025-02-05",
    bookingDate: "2025-01-15",
    status: true,
    hotelBookingRooms: [1],
    ratings: [{ id: 1, roomId: 1, rating: 5 }],
  },
  {
    id: 2,
    user: { id: 102, name: "Trần Thị B" },
    hotel: { id: 11, name: "Khách sạn Hội An Boutique" },
    checkInDate: "2025-02-10",
    checkOutDate: "2025-02-12",
    bookingDate: "2025-01-18",
    status: true,
    hotelBookingRooms: [2],
    ratings: [{ id: 2, roomId: 5, rating: 4 }],
  },
];

export const DHotelBookingRoom = [
  {
    id: 1,
    room: {
      id: 1,
      numberRoom: 101,
      roomType: "STANDARD",
      price: 100,
      maxOccupancy: 2,
      quantityRoom: 5,
      status: true,
    },
    hotelBooking: {
      id: 1,
      user: { id: 101, name: "Nguyễn Văn A" },
      hotel: { id: 11, name: "Khách sạn Hội An Boutique" },
    },
    numRoom: 2,
    pricePerRoom: 100,
  },
  {
    id: 2,
    room: {
      id: 5,
      numberRoom: 105,
      roomType: "DELUXE",
      price: 200,
      maxOccupancy: 5,
      quantityRoom: 2,
      status: true,
    },
    hotelBooking: {
      id: 2,
      user: { id: 102, name: "Trần Thị B" },
      hotel: { id: 11, name: "Khách sạn Hội An Boutique" },
    },
    numRoom: 1,
    pricePerRoom: 200,
  },
];
